#include "init.h"

   void ADC_Init(void)
{
   
    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOEEN);
    SET_BIT(RCC->APB2ENR, RCC_APB2ENR_ADC1EN);

    MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER1, GPIO_MODER_MODER1);
    MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER3, GPIO_MODER_MODER3);
    MODIFY_REG(GPIOA->PUPDR, GPIO_PUPDR_PUPDR3, 0);

    MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER4, GPIO_MODER_MODER4);
    MODIFY_REG(GPIOA->PUPDR, GPIO_PUPDR_PUPDR4, 0);
    
    CLEAR_BIT(ADC1->CR2, ADC_CR2_ADON); 
    
    SET_BIT(ADC->CCR, ADC_CCR_ADCPRE_0); 
    MODIFY_REG(ADC1->SQR1, ADC_SQR1_L, 0); 

    MODIFY_REG(ADC1->SMPR2, 
               ADC_SMPR2_SMP9 | ADC_SMPR2_SMP3 | ADC_SMPR2_SMP4, 
               (4 << ADC_SMPR2_SMP9_Pos) | (4 << ADC_SMPR2_SMP3_Pos) | (4 << ADC_SMPR2_SMP4_Pos));

    SET_BIT(ADC1->CR2, ADC_CR2_ADON);

}

uint16_t ADC_Read_Channel(uint8_t channel)
{
 
    MODIFY_REG(ADC1->SQR3, ADC_SQR3_SQ1, channel << ADC_SQR3_SQ1_Pos);

    SET_BIT(ADC1->CR2, ADC_CR2_SWSTART);
    while(!(READ_BIT(ADC1->SR, ADC_SR_EOC)));
    (void)ADC1->DR; 
    
  
    SET_BIT(ADC1->CR2, ADC_CR2_SWSTART);
    while(!(READ_BIT(ADC1->SR, ADC_SR_EOC)));
    
    return ADC1->DR;
}

void FAN_BUZZER_Init(void)
{
    SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOBEN);
    SET_BIT(RCC->APB1ENR, RCC_APB1ENR_TIM3EN); 

    GPIOB->MODER &= ~(GPIO_MODER_MODE4 | GPIO_MODER_MODE5);
    GPIOB->MODER |= (GPIO_MODER_MODE4_1 | GPIO_MODER_MODE5_1);

    GPIOB->AFR[0] &= ~(GPIO_AFRL_AFSEL4);         
    GPIOB->AFR[0] |= (0x2 << GPIO_AFRL_AFSEL4_Pos); 

    GPIOB->AFR[0] &= ~(GPIO_AFRL_AFSEL5);        
    GPIOB->AFR[0] |= (0x2 << GPIO_AFRL_AFSEL5_Pos); 

    TIM3->PSC = 89; 
    TIM3->ARR = 1000;

    TIM3->CCMR1 &= ~TIM_CCMR1_OC1M; 
    TIM3->CCMR1 |= (0x6 << TIM_CCMR1_OC1M_Pos);
    TIM3->CCMR1 |= TIM_CCMR1_OC1PE;            

    TIM3->CCMR1 &= ~TIM_CCMR1_OC2M;
    TIM3->CCMR1 |= (0x6 << TIM_CCMR1_OC2M_Pos);
    TIM3->CCMR1 |= TIM_CCMR1_OC2PE;           

    SET_BIT(TIM3->CCER, TIM_CCER_CC1E | TIM_CCER_CC2E);
    SET_BIT(TIM3->CR1, TIM_CR1_ARPE | TIM_CR1_CEN);
}


uint16_t read_POT1(void)
{
    MODIFY_REG(ADC1->SQR3, ADC_SQR3_SQ1_Msk, 0 << ADC_SQR3_SQ1_Pos);
    SET_BIT(ADC1->CR2, ADC_CR2_SWSTART);
    while (!(ADC1->SR & ADC_SR_EOC));
    return ADC1->DR;
}

uint16_t read_POT2(void)
{
    MODIFY_REG(ADC1->SQR3, ADC_SQR3_SQ1_Msk, 1 << ADC_SQR3_SQ1_Pos);
    SET_BIT(ADC1->CR2, ADC_CR2_SWSTART);
    while (!(ADC1->SR & ADC_SR_EOC));
    return ADC1->DR;
}


uint16_t read_POT3(void)
{
    SET_BIT(ADC1->CR2, ADC_CR2_SWSTART);
    while (!(ADC1->SR & ADC_SR_EOC));
    return ADC1->DR;
}